### PR TITLE
Subregions with corrected fixtures

### PR DESCRIPTION
**Pull request by adamb70**
Third time's the charm!

Replacement of #171, with added fixtures for subregions.

### CODE REVIEW

**Comment by jpic** [comment]
Thanks a heap for sharing this major contribution !

I've read a bit about it, I want to approve your patch at the condition that you watch the repo or join the club so that you can respond to users who have trouble with your feature or the upgrade.

**Comment by adamb70** [comment]
It's originally @Guts's work, so I don't want to take all the credit for it. However, I will be happy to join up and help out with any issues people might have since I am familiar with the code.

**Comment by jpic** [comment]
Right, I just thought you were the same person with different emails :joy:

**Comment by jpic** [comment]
if @max-arnold & friends don't have any objection i will merge and release on saturday :tada: 

seeyou then ;)

**Comment by Guts** [comment]
I'm a multiversed person 😉.
Thanks to achieve what I've started. I was thinking to finish it but I never never found the required time to do it.

If needed, I could monitor issues to contribute :-)

**Comment by jpic** [comment]
Released in 3.6.0

**Pull request closed without merging**
