### PR TITLE
Removed import from unicode_literals

### PR DESCRIPTION
**Pull request by smithdc1**
I got access to codespaces today so I thought I'd git it a try. I needed to add a few lines to the .gitignore file, hope these changes are acceptable -- if not happy to revert.

The main change here is removing the import from unicode_literals as I don't think this project needs Py2 support anymore.

On a similar topic -- would you like `# -*- coding: utf-8 -*-` removed? Again -- happy to add that to this PR if that would help reduce noise, but appreciate that is a slightly different change.

### CODE REVIEW

**Review by marianoeramirez — CHANGES_REQUESTED** [review]
Here maybe we should add more lines to gitignore, check here the suggested https://github.com/github/gitignore/blob/master/Global/VisualStudioCode.gitignore

**Comment by marianoeramirez** [comment]
I read this and looks like you are right, We don't anymore the '**# -*- coding: UTF-8 -*-**.  If you want, you can include this modification on the same pull request.

**Comment by smithdc1** [comment]
Think I've got them all 🤞 . I can rebase and reorder/squash the commits better later if you'd like (need to leave for now). But not sure if you squash and merge anyway.

**Comment by marianoeramirez** [comment]
Yes, I usually squash and merge. Please mark the requested as solved.

**Review by marianoeramirez — APPROVED** [review]

**Pull request merged**
